name: run Excel_converter.py

on:
  workflow_dispatch:
  schedule:
    - cron: '20 1 * * 1,2,3,4,5,6' # At 01:20, Monday - Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script and capture output filename
        id: run_script
        env:
          INVOICING_BOOK_URL: ${{ secrets.INVOICING_BOOK_URL }}
        run: |
          OUTPUT_FILE=$(python Others/Excel_converter.py | tail -n 1)
          echo "output_file=$OUTPUT_FILE" >> $GITHUB_OUTPUT

        - name: Upload File to Dropbox
          uses: ./upload-dropbox-action
          with:
            DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
            DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
            DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
            SOURCE_PATH: ${{ steps.run_script.outputs.output_file }}
            DEST_PATH: /carpeta_de_prueba/${{ steps.run_script.outputs.output_file }}
